[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "alfalfa"
version = "0.1"

[tool.ruff.lint]
ignore-init-module-imports = true

[tool.ruff.per-file-ignores]
"__init__.py" = ["F401"]